#! /bin/sh

sxhkd &

focused=#FFFFFF
unfocused=#000000

feh --bg-center ~/wallpapers/demonslayer1.png

xset +fp /home/miles/.local/share/fonts
xset fp rehash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         10
bspc config normal_border_color  $unfocused
bspc config active_border_color  $unfocused
bspc config focused_border_color $focused
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar top &
